In [ ]:
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

In [ ]:
data = load_breast_cancer()
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [ ]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [ ]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [ ]:
data['data'].shape

(569, 30)

In [ ]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
j = 0
for i in data['feature_names']:
  print(f"{i}, : {data['data'][0][j]}")
  j+=1

mean radius, : 17.99
mean texture, : 10.38
mean perimeter, : 122.8
mean area, : 1001.0
mean smoothness, : 0.1184
mean compactness, : 0.2776
mean concavity, : 0.3001
mean concave points, : 0.1471
mean symmetry, : 0.2419
mean fractal dimension, : 0.07871
radius error, : 1.095
texture error, : 0.9053
perimeter error, : 8.589
area error, : 153.4
smoothness error, : 0.006399
compactness error, : 0.04904
concavity error, : 0.05373
concave points error, : 0.01587
symmetry error, : 0.03003
fractal dimension error, : 0.006193
worst radius, : 25.38
worst texture, : 17.33
worst perimeter, : 184.6
worst area, : 2019.0
worst smoothness, : 0.1622
worst compactness, : 0.6656
worst concavity, : 0.7119
worst concave points, : 0.2654
worst symmetry, : 0.4601
worst fractal dimension, : 0.1189


In [ ]:
feature = data['data']
feature.shape

(569, 30)

In [ ]:
label = data['target']
label.shape

(569,)

In [ ]:
scaler = StandardScaler()
feature = scaler.fit_transform(feature)

In [ ]:
j = 0
for i in data['feature_names']:
  print(f"{i}, : {feature[0][j]}")
  j+=1

mean radius, : 1.0970639814699807
mean texture, : -2.0733350146975935
mean perimeter, : 1.2699336881399383
mean area, : 0.9843749048031144
mean smoothness, : 1.568466329243428
mean compactness, : 3.2835146709868264
mean concavity, : 2.652873983743168
mean concave points, : 2.532475216403245
mean symmetry, : 2.2175150059646405
mean fractal dimension, : 2.255746885296269
radius error, : 2.4897339267376193
texture error, : -0.5652650590684639
perimeter error, : 2.833030865855184
area error, : 2.4875775569611043
smoothness error, : -0.21400164666895383
compactness error, : 1.3168615683959484
concavity error, : 0.72402615808036
concave points error, : 0.6608199414286064
symmetry error, : 1.1487566671861758
fractal dimension error, : 0.9070830809973359
worst radius, : 1.8866896251792757
worst texture, : -1.3592934737640827
worst perimeter, : 2.3036006236225606
worst area, : 2.0012374893299207
worst smoothness, : 1.3076862710715387
worst compactness, : 2.616665023512603
worst concavity, : 2.1

In [ ]:
print(feature[0])
print(data['target_names'][label[20]])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
benign


In [ ]:
data['target_names'][0]

'malignant'

In [ ]:
df_ftr = pd.DataFrame(feature,columns=data['feature_names'])
df_lbl = pd.DataFrame(label,columns=['label'])
df = pd.concat([df_ftr,df_lbl],axis=1)
df = df.sample(frac=1)

In [ ]:
df

mean radius  mean texture  ...  worst fractal dimension  label
232    -0.825712      3.378983  ...                -0.602692      1
168     0.949377      1.254371  ...                 0.501745      0
77      1.114105     -0.730617  ...                 1.488146      0
33      1.460602      1.670916  ...                 1.571270      0
146    -0.660984     -0.630553  ...                 1.055903      0
..           ...           ...  ...                      ...    ...
324    -0.547378     -0.949362  ...                -0.240273      1
22      0.344426     -1.170433  ...                 0.859731      0
7      -0.118517      0.358450  ...                 1.726435      0
81     -0.223602     -0.798102  ...                 0.978321      1
483    -0.121357     -0.383884  ...                -0.794985      1

[569 rows x 31 columns]

In [ ]:
feature = df.values[:,:30]
label = df.values[:, 30:]

In [ ]:
#500 Training
X_train = feature[:500]
y_train = label[:500]
#35 Training
X_val = feature[500:535]
y_val = label[500:535]
#34 Training
X_test = feature[535:]
y_test = label[535:]

In [ ]:
model = Sequential()

model.add(Dense(64,activation = 'relu', input_dim = 30)) #add layer
model.add(Dense(32,activation = 'relu'))
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [ ]:
model.fit(X_train, y_train, batch_size=1, epochs=5,validation_data=(X_val,y_val))

Epoch 1/5
500/500 [==============================] - 1s 2ms/step - loss: 0.2055 - accuracy: 0.9380 - val_loss: 0.0715 - val_accuracy: 0.9714
Epoch 2/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0531 - accuracy: 0.9820 - val_loss: 0.0568 - val_accuracy: 0.9714
Epoch 3/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0419 - accuracy: 0.9860 - val_loss: 0.1818 - val_accuracy: 0.9429
Epoch 4/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0328 - accuracy: 0.9860 - val_loss: 0.1670 - val_accuracy: 0.9714
Epoch 5/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0221 - accuracy: 0.9940 - val_loss: 0.1228 - val_accuracy: 0.9429


In [ ]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.4181 - accuracy: 0.9412


[0.4181191325187683, 0.9411764740943909]

In [ ]:
model.evaluate(X_val,y_val)

2/2 [==============================] - 0s 5ms/step - loss: 0.1228 - accuracy: 0.9429


[0.12283676862716675, 0.9428571462631226]

In [ ]:
for i in range(10):
  sample = X_test[i]
  sample = np.reshape(sample,(1,30))

  print("Predicted")
  if model.predict(sample)[0][0] > 0.5:
    print("Benign")
  else:
    print("Malignant")


  print("Actual")

  if y_test[i] == 1:
    print("Benign\n")
  else:
    print("Malignant\n")

Predicted
Benign
Actual
Benign

Predicted
Benign
Actual
Benign

Predicted
Benign
Actual
Benign

Predicted
Benign
Actual
Benign

Predicted
Benign
Actual
Benign

Predicted
Malignant
Actual
Malignant

Predicted
Benign
Actual
Benign

Predicted
Malignant
Actual
Malignant

Predicted
Benign
Actual
Malignant

Predicted
Benign
Actual
Benign

